// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardId } from "./CardId";
import type { CardType } from "./CardType";
import type { EventId } from "./EventId";
import type { Rarity } from "./Rarity";
import type { TagId } from "./TagId";

export type Card = { card_id: CardId, name: string, card_type: CardType, tags: Array<TagId>, embedded_events: Array<EventId>, rarity: Rarity, };
