// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardType } from "./CardType";
import type { Rarity } from "./Rarity";

export type CardTemplate = { name: string, card_type: CardType, tags: Array<string>, embedded_events: Array<string>, rarity: Rarity, description: string | null, };
