// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardTypeDto } from "./CardTypeDto";

export type CardTemplateDto = { card_id: string, name: string, description: string, card_type: CardTypeDto, };
