// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardTypeValueObjectDto } from "./CardTypeValueObjectDto";
import type { RarityDto } from "./RarityDto";

export type CardDto = { card_id: string, name: string, card_type: CardTypeValueObjectDto, tags: Array<string>, embedded_events: Array<string>, rarity: RarityDto, };
