// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRecordDto } from "./SessionRecordDto";

export type CharacterDto = { character_id: string, name: string, player_id: string, personal_cards: Array<string>, acquired_tags: Array<string>, session_history: Array<SessionRecordDto>, scenario_restrictions: { [key in string]?: string }, created_at: string, last_updated: string, version: number, };
