// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { CharacterId } from "./CharacterId";
import type { RestrictionReason } from "./RestrictionReason";
import type { ScenarioId } from "./ScenarioId";
import type { SessionRecord } from "./SessionRecord";
import type { Tag } from "./Tag";
import type { UserId } from "./UserId";

export interface Character { character_id: CharacterId, name: string, player_id: UserId, personal_cards: Array<Card>, acquired_tags: Array<Tag>, session_history: Array<SessionRecord>, scenario_restrictions: Record<ScenarioId, RestrictionReason>, created_at: string, last_updated: string, }