// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompletionCondition = { condition_type: string, parameters: { [key in string]?: string }, };
