// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { Tag } from "./Tag";
import type { UserId } from "./UserId";

export interface CreateCharacterRequest { name: string, player_id: UserId, initial_cards: Array<Card> | null, initial_tags: Array<Tag> | null, }