// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvantageType } from "./AdvantageType";

export interface DiceNotation { dice_count: number, dice_sides: number, modifier: number, advantage: AdvantageType, }