// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiceNotation } from "./DiceNotation";

export type DiceResult = { notation: DiceNotation, raw_rolls: Array<number>, final_result: number, success: boolean, timestamp: string, };
