// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiceNotation } from "./DiceNotation";

export type DiceNotationParseResult = { success: boolean, notation: DiceNotation | null, error: string | null, };
