// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from "./EventId";
import type { GameSessionEvent } from "./GameSessionEvent";
import type { SessionId } from "./SessionId";

export type DomainEvent = { event_id: EventId, session_id: SessionId, timestamp: string, event_type: GameSessionEvent, version: number, };
