// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventEffect } from "./EventEffect";
import type { EventId } from "./EventId";
import type { EventTrigger } from "./EventTrigger";
import type { EventType } from "./EventType";

export type EventDefinition = { event_id: EventId, name: string, event_type: EventType, triggers: Array<EventTrigger>, effects: Array<EventEffect>, message: string, };
