// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { ScenarioId } from "./ScenarioId";
import type { SceneId } from "./SceneId";
import type { SessionStatus } from "./SessionStatus";
import type { UserId } from "./UserId";

export type GameSessionEvent = { "session_created": { scenario_id: ScenarioId, gm_user_id: UserId, } } | { "player_added": { player_id: PlayerId, user_id: UserId, } } | { "session_started": { current_scene: SceneId, } } | { "session_status_changed": { new_status: SessionStatus, } };
