// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { PlayerId } from "./PlayerId";
import type { ScenarioId } from "./ScenarioId";
import type { SceneId } from "./SceneId";
import type { SessionId } from "./SessionId";
import type { SessionPlayer } from "./SessionPlayer";
import type { SessionStatus } from "./SessionStatus";
import type { UserId } from "./UserId";

export interface GameSession { session_id: SessionId, scenario_id: ScenarioId, gm_user_id: UserId, created_at: string, players: Record<PlayerId, SessionPlayer>, max_players: number, current_scene: SceneId, shared_cards: Array<Card>, session_status: SessionStatus, version: bigint, }