// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerStatusDto = "waiting" | "active" | { "inactive": { duration_minutes: number, } } | "departed";
