// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardTemplate } from "./CardTemplate";
import type { Difficulty } from "./Difficulty";
import type { PlayerRange } from "./PlayerRange";
import type { ScenarioId } from "./ScenarioId";
import type { SceneDefinition } from "./SceneDefinition";
import type { SceneId } from "./SceneId";
import type { UserId } from "./UserId";

export interface ScenarioTemplate { scenario_id: ScenarioId, name: string, description: string, author_id: UserId, version: string, recommended_players: PlayerRange, estimated_duration_minutes: number, difficulty: Difficulty, tags: Array<string>, scenes: Record<SceneId, SceneDefinition>, initial_scene_id: SceneId, shared_cards: Array<CardTemplate>, derived_from: ScenarioId | null, version_number: bigint, }