// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SceneDefinitionDto = { scene_id: string, name: string, description: string, objectives: Array<string>, completion_conditions: Array<string>, };
