// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";

export interface SceneTransition { from_scene: SceneId, to_scene: SceneId, condition: string, }