// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionCondition } from "./CompletionCondition";
import type { EventDefinition } from "./EventDefinition";
import type { EventId } from "./EventId";
import type { SceneId } from "./SceneId";
import type { SceneTransition } from "./SceneTransition";

export interface SceneDefinition { scene_id: SceneId, name: string, description: string, objective: string, completion_condition: CompletionCondition, events: Record<EventId, EventDefinition>, transitions: Array<SceneTransition>, }