// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { ScenarioId } from "./ScenarioId";
import type { SessionId } from "./SessionId";
import type { Tag } from "./Tag";

export interface SessionRecord { session_id: SessionId, scenario_id: ScenarioId, participated_at: string, final_tags: Array<Tag>, final_cards: Array<Card>, feedback: string | null, }