// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionStatusDto = "created" | "waiting_for_players" | "recruiting" | "starting" | { "in_progress": { current_scene: string, active_players: Array<string>, } } | "paused" | "completed" | "terminated";
