// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { SceneId } from "./SceneId";

export type SessionStatus = "created" | "recruiting" | "starting" | { "in_progress": { current_scene: SceneId, active_players: Array<PlayerId>, } } | "paused" | "completed" | "terminated";