// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionRecordDto = { session_id: string, scenario_id: string, participated_at: string, final_tags: Array<string>, final_cards: Array<string>, feedback: string | null, };
