// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { CharacterId } from "./CharacterId";
import type { CharacterStatus } from "./CharacterStatus";
import type { Tag } from "./Tag";

export type SessionCharacter = { character_id: CharacterId, name: string, session_cards: Array<Card>, session_tags: Array<Tag>, status: CharacterStatus, };
