// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerStatusDto } from "./PlayerStatusDto";

export type SessionPlayerDto = { id: string, user_id: string, character: string | null, status: PlayerStatusDto, joined_at: string, };
