// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { PlayerStatus } from "./PlayerStatus";
import type { SessionCharacter } from "./SessionCharacter";
import type { UserId } from "./UserId";

export type SessionPlayer = { id: PlayerId, user_id: UserId, character: SessionCharacter | null, status: PlayerStatus, joined_at: string, };
