// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagCategory } from "./TagCategory";
import type { TagId } from "./TagId";
import type { TagValue } from "./TagValue";

export interface Tag { tag_id: TagId, name: string, category: TagCategory, value: TagValue | null, }