// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagId } from "./TagId";
import type { TagOperation } from "./TagOperation";
import type { TagValue } from "./TagValue";

export type TagModification = { tag_id: TagId, operation: TagOperation, new_value: TagValue | null, };
